site_name: HCPSS School Site
theme:
  name: material
markdown_extensions:
  - admonition
  - def_list
  - attr_list
  - toc:
      permalink: "#"
plugins:
  - mkdocs-video:
      is_video: True
      video_autoplay: False
      video_loop: True
      video_muted: True
      css_style:
        width: "100%"
        height: "32vw"
nav:
  - index.md
  - logging-in.md
  - tips-and-best-practices.md
  - finding-content.md
  - Creating and Managing Content:
    - News: creating-and-editing-news-messages.md
    - Events: creating-and-editing-events.md
    - Staff Lists: creating-and-managing-staff-lists.md
  - Advanced Topics:
    - Media: adding-and-managing-media.md
    - Homepage Highlights: managing-homepage-highlights.md
    - Cloning Content: clone-content.md
    - Newsletters: creating-newsletter.md
  - faq.md
extra_css:
  - stylesheets/extra.css
